// <auto-generated />
using ContactManager.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ContactManager.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

        modelBuilder.Entity("ContactManager.Models.Person", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("DateOfBirth").HasColumnType("TEXT");
            b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
            b.Property<string>("FirstName").IsRequired().HasColumnType("TEXT");
            b.Property<bool>("Gender").HasColumnType("INTEGER");
            b.Property<bool>("IsActive").HasColumnType("INTEGER");
            b.Property<string>("LastName").IsRequired().HasColumnType("TEXT");
            b.Property<string>("Nationality").IsRequired().HasColumnType("TEXT");
            b.Property<string>("PhoneNumberBusiness").IsRequired().HasColumnType("TEXT");
            b.Property<string>("PhoneNumberMobile").IsRequired().HasColumnType("TEXT");
            b.Property<string>("PhoneNumberPrivate").IsRequired().HasColumnType("TEXT");
            b.Property<string>("Place").IsRequired().HasColumnType("TEXT");
            b.Property<string>("Salutation").IsRequired().HasColumnType("TEXT");
            b.Property<string>("SocialSecurityNumber").IsRequired().HasColumnType("TEXT");
            b.Property<string>("Street").IsRequired().HasColumnType("TEXT");
            b.Property<string>("StreetNumber").IsRequired().HasColumnType("TEXT");
            b.Property<string>("Title").IsRequired().HasColumnType("TEXT");
            b.Property<int>("ZipCode").HasColumnType("INTEGER");
            b.Property<string>("PersonType").IsRequired().HasMaxLength(8).HasColumnType("TEXT");
            b.HasKey("Id");
            b.ToTable("Persons");
            b.HasDiscriminator<string>("PersonType");
        });

        modelBuilder.Entity("ContactManager.Models.Customer", b =>
        {
            b.HasBaseType("ContactManager.Models.Person");
            b.Property<string>("BusinessAddress").IsRequired().HasColumnType("TEXT");
            b.Property<string>("CompanyContact").IsRequired().HasColumnType("TEXT");
            b.Property<string>("CompanyName").IsRequired().HasColumnType("TEXT");
            b.Property<char>("CustomerType").HasColumnType("TEXT");
            b.HasDiscriminator().HasValue("Customer");
        });

        modelBuilder.Entity("ContactManager.Models.Employee", b =>
        {
            b.HasBaseType("ContactManager.Models.Person");
            b.Property<int>("CadreLevel").HasColumnType("INTEGER");
            b.Property<string>("Department").IsRequired().HasColumnType("TEXT");
            b.Property<Guid>("EmployeeNumber").HasColumnType("TEXT");
            b.Property<DateTime?>("EndDate").HasColumnType("TEXT");
            b.Property<int>("Employment").HasColumnType("INTEGER");
            b.Property<string>("Role").IsRequired().HasColumnType("TEXT");
            b.Property<DateTime>("StartDate").HasColumnType("TEXT");
            b.HasIndex("EmployeeNumber").IsUnique();
            b.HasDiscriminator().HasValue("Employee");
        });

        modelBuilder.Entity("ContactManager.Models.Trainee", b =>
        {
            b.HasBaseType("ContactManager.Models.Employee");
            b.Property<int>("ActualTraineeYear").HasColumnType("INTEGER");
            b.Property<int>("TraineeYears").HasColumnType("INTEGER");
            b.HasDiscriminator().HasValue("Trainee");
        });

        modelBuilder.Entity("ContactManager.Models.CustomerContactNote", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
            b.Property<int>("CustomerId").HasColumnType("INTEGER");
            b.Property<string>("NoteText").IsRequired().HasColumnType("TEXT");
            b.HasKey("Id");
            b.HasIndex("CustomerId");
            b.ToTable("CustomerContactNotes");
        });

        modelBuilder.Entity("ContactManager.Models.CustomerContactNote", b =>
        {
            b.HasOne("ContactManager.Models.Customer", "Customer")
                .WithMany("ContactNotes")
                .HasForeignKey("CustomerId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Customer");
        });

        modelBuilder.Entity("ContactManager.Models.Customer", b =>
        {
            b.Navigation("ContactNotes");
        });
#pragma warning restore 612, 618
    }
}
